# coding: utf-8
from sqlalchemy import CHAR, Column, VARCHAR
from sqlalchemy.dialects.oracle import NUMBER
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class TO32Stockinfo(Base):
    __tablename__ = 't_o32_stockinfo'

    l_date = Column(NUMBER(8, 0, False), primary_key=True, nullable=False)
    vc_inter_code = Column(VARCHAR(8), primary_key=True, nullable=False)
    c_market_no = Column(CHAR(1), nullable=False)
    vc_report_code = Column(VARCHAR(20), nullable=False)
    vc_stock_name = Column(VARCHAR(100), nullable=False)
    vc_stock_spell = Column(VARCHAR(4))
    c_stock_type = Column(VARCHAR(2))
    c_asset_class = Column(CHAR(1), nullable=False)
    en_uplimited_ratio = Column(VARCHAR(50), nullable=False)
    en_downlimited_ratio = Column(VARCHAR(50), nullable=False)
    en_uplimited_price = Column(VARCHAR(50), nullable=False)
    en_downlimited_price = Column(VARCHAR(50), nullable=False)
    l_uplimited_amount = Column(VARCHAR(50), nullable=False)
    l_downlimited_amount = Column(VARCHAR(50), nullable=False)
    c_default_price = Column(CHAR(1), nullable=False)
    vc_frozen_code = Column(VARCHAR(8), nullable=False)
    vc_relative_frozen_code = Column(VARCHAR(8), nullable=False)
    vc_assign_code = Column(VARCHAR(8), nullable=False)
    vc_asset_relative_code = Column(VARCHAR(8), nullable=False)
    vc_match_relative1_code = Column(VARCHAR(8), nullable=False)
    vc_match_relative2_code = Column(VARCHAR(8), nullable=False)
    l_total_amount = Column(NUMBER(16, 0, False), nullable=False)
    l_turnover_amount = Column(NUMBER(16, 0, False), nullable=False)
    en_repay_year = Column(VARCHAR(50), nullable=False)
    en_yesterday_close_price = Column(VARCHAR(50), nullable=False)
    en_open_price = Column(VARCHAR(50), nullable=False)
    l_company_id = Column(NUMBER(10, 0, False))
    en_yield_ratio = Column(VARCHAR(50))
    vc_mixed_type = Column(VARCHAR(100))
    l_near_amount = Column(NUMBER(16, 0, False))
    l_publish_date = Column(NUMBER(8, 0, False))
    l_turnover_date = Column(NUMBER(8, 0, False))
    l_total_lock_days = Column(NUMBER(8, 0, False))
    l_left_lock_days = Column(NUMBER(8, 0, False))
    en_face_values = Column(VARCHAR(50), nullable=False)
    vc_stock_fullname = Column(VARCHAR(256))
    c_stop_flag = Column(CHAR(1), nullable=False)
    en_last_price = Column(VARCHAR(50), nullable=False)
    en_avg_price = Column(VARCHAR(50), nullable=False)
    en_max_price = Column(VARCHAR(50), nullable=False)
    en_min_price = Column(VARCHAR(50), nullable=False)
    l_market_deal_amount = Column(VARCHAR(50), nullable=False)
    en_market_deal_balance = Column(VARCHAR(50), nullable=False)
    en_reference_price = Column(VARCHAR(50))
    vc_international_code = Column(VARCHAR(32))
    vc_price_relative_code = Column(VARCHAR(8))
    vc_ric_code = Column(VARCHAR(32))
    vc_sedol_code = Column(VARCHAR(32))
    vc_cusip_code = Column(VARCHAR(32))
    en_buy_price1 = Column(VARCHAR(50))
    l_buy_amount1 = Column(NUMBER(16, 0, False))
    en_buy_price2 = Column(VARCHAR(50))
    l_buy_amount2 = Column(NUMBER(16, 0, False))
    en_buy_price3 = Column(VARCHAR(50))
    l_buy_amount3 = Column(NUMBER(16, 0, False))
    en_buy_price4 = Column(VARCHAR(50))
    l_buy_amount4 = Column(NUMBER(16, 0, False))
    en_buy_price5 = Column(VARCHAR(50))
    l_buy_amount5 = Column(NUMBER(16, 0, False))
    en_sale_price1 = Column(VARCHAR(50))
    l_sale_amount1 = Column(NUMBER(16, 0, False))
    en_sale_price2 = Column(VARCHAR(50))
    l_sale_amount2 = Column(NUMBER(16, 0, False))
    en_sale_price3 = Column(VARCHAR(50))
    l_sale_amount3 = Column(NUMBER(16, 0, False))
    en_sale_price4 = Column(VARCHAR(50))
    l_sale_amount4 = Column(NUMBER(16, 0, False))
    en_sale_price5 = Column(VARCHAR(50))
    l_sale_amount5 = Column(NUMBER(16, 0, False))
    vc_currency_no = Column(VARCHAR(3), nullable=False)
    l_listing_date = Column(NUMBER(8, 0, False))
    c_long_stop_flag = Column(CHAR(1), nullable=False)
    en_fair_price2 = Column(VARCHAR(50), nullable=False)
    vc_actual_code = Column(VARCHAR(20))
    l_buy_unit = Column(VARCHAR(50), nullable=False)
    l_sale_unit = Column(VARCHAR(50), nullable=False)
    vc_issue_country = Column(VARCHAR(3))
    vc_risk_country = Column(VARCHAR(3))
    vc_bloomberg_code = Column(VARCHAR(32))
    l_wx_listing_date = Column(NUMBER(8, 0, False))
    l_add_date = Column(NUMBER(8, 0, False))
    vc_busin_classes = Column(VARCHAR(512))
    en_estimate_prob = Column(VARCHAR(50))
    vc_trade_currency_no = Column(VARCHAR(3), nullable=False)
    vc_accountant_stock_code = Column(VARCHAR(6))
    c_interest_mode = Column(CHAR(1))
    l_underwriter_id = Column(VARCHAR(2000))
    vc_fund_shr_class = Column(VARCHAR(8))
    en_initestimate_prob = Column(VARCHAR(50))
    en_venueestimate_prob = Column(VARCHAR(50))
    en_right_price = Column(VARCHAR(50))
    c_ipo_marketcap = Column(CHAR(1))
    vc_reference_fa_code = Column(VARCHAR(8))
    vc_contractid_id = Column(VARCHAR(20))
    l_virtual_key = Column(NUMBER(16, 0, False))
    vc_timestamp = Column(VARCHAR(20))
    c_attorn_type = Column(CHAR(1))
    l_amount_per_hand = Column(NUMBER(10, 0, False))
    vc_custom_class = Column(VARCHAR(4000))
    c_trade_active = Column(CHAR(1))
    c_bs_flag = Column(CHAR(1))
    c_zrzt = Column(CHAR(1))
    c_cqcx = Column(CHAR(1))
    l_zsssl = Column(NUMBER(10, 0, False))
    en_zzd_price = Column(VARCHAR(50))
    en_zzd_price2 = Column(VARCHAR(50))
    en_zz_price = Column(VARCHAR(50))
    en_zz_price2 = Column(VARCHAR(50))
    c_hzjy_flag = Column(CHAR(1))
    c_stock_fee_type = Column(CHAR(1))
    vc_layering = Column(CHAR(1))
    c_trading_phase = Column(CHAR(1))
    l_issue_total_amount = Column(NUMBER(16, 0, False))
    vc_mother_company_ids = Column(VARCHAR(2000))
    en_lowest_inquery_value = Column(VARCHAR(50))
    c_noprofit = Column(CHAR(1))
    c_voterights = Column(CHAR(1))
    c_stock_property = Column(CHAR(1))
    c_cdr_market_no = Column(CHAR(1))
    vc_md5 = Column(VARCHAR(32))

    def __str__(self):
        return  str(self.l_date)+str(self.vc_inter_code)+'$*'+str(self.vc_md5)